namespace Microsoft.Zune.Service
{
	public enum EServiceEndpointId
	{
		SEID_EndpointMax = 37,
		SEID_DownloadQoS = 36,
		SEID_TermsOfService = 35,
		SEID_AppReview = 34,
		SEID_MBRTelemetry = 33,
		SEID_Stats = 0x20,
		SEID_MyPhone = 0x1F,
		SEID_ImageCatalog = 30,
		SEID_AuthTransfer = 29,
		SEID_Comments = 28,
		SEID_UsageMembers = 27,
		SEID_QuickMixSecure = 26,
		SEID_QuickMix = 25,
		SEID_CommerceV3 = 24,
		SEID_CommerceV2 = 23,
		SEID_Commerce = 22,
		SEID_PicksDogfood = 21,
		SEID_WindowsLiveSignup = 20,
		SEID_Billing = 19,
		SEID_Telemetry = 18,
		SEID_RootCatalogSSL = 17,
		SEID_RootCatalog = 0x10,
		SEID_WMISEndpoints = 0xF,
		SEID_Tuners = 14,
		SEID_Resources = 13,
		SEID_ZuneNet = 12,
		SEID_WMISRedirEndpoint = 11,
		SEID_WMISImageEndpoint = 10,
		SEID_UsageData = 9,
		SEID_Transaction = 8,
		SEID_Recommendations = 7,
		SEID_Passport = 6,
		SEID_Messaging = 5,
		SEID_Lynx = 4,
		SEID_SocialApi = 3,
		SEID_Forums = 2,
		SEID_AccountManagement = 1,
		SEID_Invalid = 0
	}
}
