using System.Runtime.InteropServices;

namespace ZuneUI
{
	public struct HRESULT
	{
		public int hr;

		public static HRESULT _S_OK;

		public static HRESULT _S_FALSE;

		public static HRESULT _E_ABORT;

		public static HRESULT _E_PENDING;

		public static HRESULT _E_FAIL;

		public static HRESULT _E_UNEXPECTED;

		public static HRESULT _E_ACCESSDENIED;

		public static HRESULT _ERROR_SERVICE_DISABLED;

		public static HRESULT _NS_E_WMP_UNKNOWN_ERROR;

		public static HRESULT _NS_E_WMP_PLAYLIST_IMPORT_ERROR;

		public static HRESULT _NS_E_CD_BUSY;

		public static HRESULT _E_ALREADY_EXISTS;

		public static HRESULT _DB_E_NOTFOUND;

		public static HRESULT _DB_E_RESOURCEEXISTS;

		public static HRESULT _DB_E_BADPARAMETERNAME;

		public static HRESULT _ZUNE_E_NO_AVAILABLE_RESTORE_POINT;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_UNKNOWN;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_RUNNING;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_NO_CONFIG;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_ASSOCIATE;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_DHCP;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_TIMEOUT;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_CANCELLED;

		public static HRESULT _NS_E_MTPZ_WLAN_TEST_FAIL_INTERNAL;

		public static HRESULT _ZEST_E_TOO_MANY_DEREGISTRATIONS_WITHIN_MONTH;

		public static HRESULT _NS_E_MEDIA_DOWNLOAD_MAXIMUM_EXCEEDED;

		public static HRESULT _ZUNE_E_NO_SUBSCRIPTION_DOWNLOAD_RIGHTS;

		public static HRESULT _NS_E_MEDIA_NOT_PURCHASED;

		public static HRESULT _NS_E_MESSAGING_CLIENT_ERROR;

		public static HRESULT _NS_E_MESSAGING_RECIPIENT_ERROR;

		public static HRESULT _NS_E_MESSAGING_PARENTAL_CONTROL_ERROR;

		public static HRESULT _NS_E_CART_FULL;

		public static HRESULT _NS_E_CART_TOO_MANY_NEW_ITEMS;

		public static HRESULT _NS_E_CART_MORE_ITEMS_AVAILABLE;

		public static HRESULT _NS_E_SIGNIN_TERMS_OF_SERVICE;

		public static HRESULT _NS_E_SERVER_ACCESSDENIED;

		public static HRESULT _NS_E_PASSPORT_LOGIN_FAILED;

		public static HRESULT _NS_E_SUBSCRIPTIONSERVICE_LOGIN_FAILED;

		public static HRESULT _NS_E_INVALID_USERNAME_AND_PASSWORD;

		public static HRESULT _NS_E_SIGNIN_ACCOUNTS_INVALID_USER;

		public static HRESULT _NS_E_SIGNIN_ACCOUNTS_NOT_XENON_USER;

		public static HRESULT _NS_E_SIGNIN_WCMUSIC_ACCOUNT_NOT_ELIGIBLE;

		public static HRESULT _ZUNE_E_SIGNIN_TERMS_OF_SERVICE_CHILD;

		public static HRESULT _NS_E_SIGNIN_INVALID_REGION;

		public static HRESULT _ZEST_E_UNAUTHENTICATED;

		public static HRESULT _NS_E_SIGNIN_HTTP_GONE;

		public static HRESULT _NS_E_BILLING_LIGHTWEIGHT_ACCOUNT;

		public static HRESULT _NS_E_FIRMWARE_UPDATE_DISK_FULL;

		public static HRESULT _NS_E_WINLIVE_SIGNIN_NAME_TOO_SHORT;

		public static HRESULT _NS_E_WINLIVE_SIGNIN_NAME_TOO_LONG;

		public static HRESULT _NS_E_WINLIVE_SIGNIN_NAME_INVALID;

		public static HRESULT _NS_E_WINLIVE_EMAIL_INVALID;

		public static HRESULT _NS_E_WINLIVE_NAME_INVALID;

		public static HRESULT _NS_E_WINLIVE_BIRTH_YEAR_INVALID;

		public static HRESULT _NS_E_WINLIVE_BIRTH_DAY_INVALID;

		public static HRESULT _NS_E_WINLIVE_BIRTH_MONTH_INVALID;

		public static HRESULT _NS_E_WINLIVE_BIRTH_DATE_FUTURE;

		public static HRESULT _NS_E_WINLIVE_HIP_SOLUTION_INVALID;

		public static HRESULT _NS_E_WINLIVE_PASSWORD_TOO_LONG;

		public static HRESULT _NS_E_WINLIVE_PASSWORD_TOO_SHORT;

		public static HRESULT _NS_E_WINLIVE_PASSWORD_INVALID;

		public static HRESULT _NS_E_WINLIVE_MEMBER_EXISTS;

		public static HRESULT _NS_E_WINLIVE_DOMAIN_IS_MANAGED;

		public static HRESULT _NS_E_WINLIVE_SECRET_QUESTION_TOO_SHORT;

		public static HRESULT _NS_E_WINLIVE_SECRET_QUESTION_TOO_LONG;

		public static HRESULT _NS_E_WINLIVE_SECRET_ANSWER_TOO_SHORT;

		public static HRESULT _NS_E_WINLIVE_SECRET_ANSWER_TOO_LONG;

		public static HRESULT _NS_E_WINLIVE_SECRET_QUESTION_CONTAINS_ANSWER;

		public static HRESULT _NS_E_WINLIVE_SECRET_ANSWER_CONTAINS_MEMBER_NAME;

		public static HRESULT _NS_E_WINLIVE_SECRET_ANSWER_CONTAINS_PASSWORD;

		public static HRESULT _NS_E_WINLIVE_SECRET_QUESTION_CONTAINS_PASSWORD;

		public static HRESULT _ZUNE_E_WINLIVE_UNAUTHORIZED_DOMAIN;

		public static HRESULT _ZEST_E_ACCOUNT_ZUNETAG_OCCUPIED;

		public static HRESULT _ZUNE_E_SIGNUP_INVALID_PARENT_EMAIL;

		public static HRESULT _ZUNE_E_SIGNUP_INVALID_PARENT_AGE;

		public static HRESULT _ZUNE_E_SIGNUP_PASSWORDS_DONT_MATCH;

		public static HRESULT _ZUNE_E_UPDATE_ACCOUNT_INFO_FAILED;

		public static HRESULT _ZEST_E_INVALID_POSTALCODE;

		public static HRESULT _ZEST_E_LIVEACCOUNT_INVALIDPHONE;

		public static HRESULT _ZEST_E_LIVEACCOUNT_ADDRESS_INVALID;

		public static HRESULT _ZEST_E_LIVEACCOUNT_PAYMENT_INSTRUMENT_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_ADDRESS_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_ADDRESS_STREET1_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_ADDRESS_CITY_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_ADDRESS_STATE_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_ADDRESS_POSTALCODE_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_PARENTPHONE_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_INVALID;

		public static HRESULT _ZEST_E_CREDITCARD_VALIDATE_FAILED;

		public static HRESULT _ZEST_E_CREDITCARD_ADD_FAILED;

		public static HRESULT _ZEST_E_INVALID_ARG_ZUNETAG;

		public static HRESULT _ZEST_E_INVALID_ARG_PARENT_PHONE_INVALID;

		public static HRESULT _ZEST_E_INVALID_ARG_CONTACT_INFO;

		public static HRESULT _ZEST_E_INVALID_ARG_LANGUAGE;

		public static HRESULT _ZEST_E_ZUNETAG_OFFENSIVE;

		public static HRESULT _ZUNE_E_PURCHASE_REQUIRES_AUTHORIZATION;

		public static HRESULT _ZEST_E_PARTNER_SERVICE_UNKNOWN_ERROR;

		public static HRESULT _NS_E_DRM_RENTAL_LICENSE_EXPIRED;

		public static HRESULT _NS_E_DRM_LICENSE_ALREADY_ACQUIRED;

		public static HRESULT _NS_E_DRM_DEVICE_RENTAL_LICENSE;

		public static HRESULT _ZUNE_E_CONTENT_NOT_SUPPORTED_ON_TUNER;

		public static HRESULT _ZUNE_E_QUICKMIX_MEDIA_NOT_FOUND;

		public static HRESULT _ZUNE_E_QUICKMIX_SESSION_IN_USE;

		public static HRESULT _ZUNE_E_UNKNOWN_REGION_OR_LANGUAGE;

		public static HRESULT _NS_E_CURL_INVALIDCHAR;

		public static HRESULT _NS_E_CURL_INVALIDPATH;

		public static HRESULT _ZUNE_E_ADD_REVIEW_FAILED;

		public static HRESULT _ZEST_E_MAX_CONCURRENTSTREAMING_EXCEEDED;

		public static HRESULT _ZEST_E_MULTITUNER_CONCURRENTSTREAMING_DETECTED;

		public static HRESULT _ZEST_E_MEDIAINSTANCE_STREAMING_OCCUPIED;

		public int Int => hr;

		public bool IsSuccess
		{
			[return: MarshalAs(UnmanagedType.U1)]
			get
			{
				return (byte)((hr >= 0) ? 1u : 0u) != 0;
			}
		}

		public bool IsError
		{
			[return: MarshalAs(UnmanagedType.U1)]
			get
			{
				return hr < 0;
			}
		}

		public HRESULT(int hr)
		{
			this.hr = hr;
		}

		[return: MarshalAs(UnmanagedType.U1)]
		public static bool operator ==(HRESULT hrA, HRESULT hrB)
		{
			return hrA.hr == hrB.hr;
		}

		[return: MarshalAs(UnmanagedType.U1)]
		public static bool operator !=(HRESULT hrA, HRESULT hrB)
		{
			return (byte)((hrA.hr != hrB.hr) ? 1u : 0u) != 0;
		}

		public static implicit operator HRESULT(int hr)
		{
			HRESULT result;
			result.hr = hr;
			return result;
		}

		[return: MarshalAs(UnmanagedType.U1)]
		public override bool Equals(object oCompare)
		{
			int num = ((oCompare is HRESULT && hr == ((HRESULT)oCompare).hr) ? 1 : 0);
			return (byte)num != 0;
		}

		public override int GetHashCode()
		{
			return hr;
		}

		public override string ToString()
		{
			int num = hr;
			return "hr:" + num.ToString("X");
		}

		static HRESULT()
		{
			HRESULT s_OK;
			s_OK.hr = 0;
			_S_OK = s_OK;
			HRESULT s_FALSE;
			s_FALSE.hr = 1;
			_S_FALSE = s_FALSE;
			HRESULT e_ABORT;
			e_ABORT.hr = -2147467260;
			_E_ABORT = e_ABORT;
			HRESULT e_PENDING;
			e_PENDING.hr = -2147483638;
			_E_PENDING = e_PENDING;
			HRESULT e_FAIL;
			e_FAIL.hr = -2147467259;
			_E_FAIL = e_FAIL;
			HRESULT e_UNEXPECTED;
			e_UNEXPECTED.hr = -2147418113;
			_E_UNEXPECTED = e_UNEXPECTED;
			HRESULT e_ACCESSDENIED;
			e_ACCESSDENIED.hr = -2147024891;
			_E_ACCESSDENIED = e_ACCESSDENIED;
			HRESULT eRROR_SERVICE_DISABLED;
			eRROR_SERVICE_DISABLED.hr = 1058;
			_ERROR_SERVICE_DISABLED = eRROR_SERVICE_DISABLED;
			HRESULT nS_E_WMP_UNKNOWN_ERROR;
			nS_E_WMP_UNKNOWN_ERROR.hr = -1072885299;
			_NS_E_WMP_UNKNOWN_ERROR = nS_E_WMP_UNKNOWN_ERROR;
			HRESULT nS_E_WMP_PLAYLIST_IMPORT_ERROR;
			nS_E_WMP_PLAYLIST_IMPORT_ERROR.hr = -1072885765;
			_NS_E_WMP_PLAYLIST_IMPORT_ERROR = nS_E_WMP_PLAYLIST_IMPORT_ERROR;
			HRESULT nS_E_CD_BUSY;
			nS_E_CD_BUSY.hr = -1072885764;
			_NS_E_CD_BUSY = nS_E_CD_BUSY;
			HRESULT e_ALREADY_EXISTS;
			e_ALREADY_EXISTS.hr = -2147024713;
			_E_ALREADY_EXISTS = e_ALREADY_EXISTS;
			HRESULT dB_E_NOTFOUND;
			dB_E_NOTFOUND.hr = -2147217895;
			_DB_E_NOTFOUND = dB_E_NOTFOUND;
			HRESULT dB_E_RESOURCEEXISTS;
			dB_E_RESOURCEEXISTS.hr = -2147217768;
			_DB_E_RESOURCEEXISTS = dB_E_RESOURCEEXISTS;
			HRESULT dB_E_BADPARAMETERNAME;
			dB_E_BADPARAMETERNAME.hr = -2147217827;
			_DB_E_BADPARAMETERNAME = dB_E_BADPARAMETERNAME;
			HRESULT zUNE_E_NO_AVAILABLE_RESTORE_POINT;
			zUNE_E_NO_AVAILABLE_RESTORE_POINT.hr = -1056899026;
			_ZUNE_E_NO_AVAILABLE_RESTORE_POINT = zUNE_E_NO_AVAILABLE_RESTORE_POINT;
			HRESULT nS_E_MTPZ_WLAN_TEST_UNKNOWN;
			nS_E_MTPZ_WLAN_TEST_UNKNOWN.hr = -1072887866;
			_NS_E_MTPZ_WLAN_TEST_UNKNOWN = nS_E_MTPZ_WLAN_TEST_UNKNOWN;
			HRESULT nS_E_MTPZ_WLAN_TEST_RUNNING;
			nS_E_MTPZ_WLAN_TEST_RUNNING.hr = -1072887865;
			_NS_E_MTPZ_WLAN_TEST_RUNNING = nS_E_MTPZ_WLAN_TEST_RUNNING;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_NO_CONFIG;
			nS_E_MTPZ_WLAN_TEST_FAIL_NO_CONFIG.hr = -1072887864;
			_NS_E_MTPZ_WLAN_TEST_FAIL_NO_CONFIG = nS_E_MTPZ_WLAN_TEST_FAIL_NO_CONFIG;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_ASSOCIATE;
			nS_E_MTPZ_WLAN_TEST_FAIL_ASSOCIATE.hr = -1072887863;
			_NS_E_MTPZ_WLAN_TEST_FAIL_ASSOCIATE = nS_E_MTPZ_WLAN_TEST_FAIL_ASSOCIATE;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_DHCP;
			nS_E_MTPZ_WLAN_TEST_FAIL_DHCP.hr = -1072887862;
			_NS_E_MTPZ_WLAN_TEST_FAIL_DHCP = nS_E_MTPZ_WLAN_TEST_FAIL_DHCP;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_TIMEOUT;
			nS_E_MTPZ_WLAN_TEST_FAIL_TIMEOUT.hr = -1072887861;
			_NS_E_MTPZ_WLAN_TEST_FAIL_TIMEOUT = nS_E_MTPZ_WLAN_TEST_FAIL_TIMEOUT;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_CANCELLED;
			nS_E_MTPZ_WLAN_TEST_FAIL_CANCELLED.hr = -1072887860;
			_NS_E_MTPZ_WLAN_TEST_FAIL_CANCELLED = nS_E_MTPZ_WLAN_TEST_FAIL_CANCELLED;
			HRESULT nS_E_MTPZ_WLAN_TEST_FAIL_INTERNAL;
			nS_E_MTPZ_WLAN_TEST_FAIL_INTERNAL.hr = -1072887859;
			_NS_E_MTPZ_WLAN_TEST_FAIL_INTERNAL = nS_E_MTPZ_WLAN_TEST_FAIL_INTERNAL;
			HRESULT zEST_E_TOO_MANY_DEREGISTRATIONS_WITHIN_MONTH;
			zEST_E_TOO_MANY_DEREGISTRATIONS_WITHIN_MONTH.hr = -1056857072;
			_ZEST_E_TOO_MANY_DEREGISTRATIONS_WITHIN_MONTH = zEST_E_TOO_MANY_DEREGISTRATIONS_WITHIN_MONTH;
			HRESULT nS_E_MEDIA_DOWNLOAD_MAXIMUM_EXCEEDED;
			nS_E_MEDIA_DOWNLOAD_MAXIMUM_EXCEEDED.hr = -1072884900;
			_NS_E_MEDIA_DOWNLOAD_MAXIMUM_EXCEEDED = nS_E_MEDIA_DOWNLOAD_MAXIMUM_EXCEEDED;
			HRESULT zUNE_E_NO_SUBSCRIPTION_DOWNLOAD_RIGHTS;
			zUNE_E_NO_SUBSCRIPTION_DOWNLOAD_RIGHTS.hr = -1056899031;
			_ZUNE_E_NO_SUBSCRIPTION_DOWNLOAD_RIGHTS = zUNE_E_NO_SUBSCRIPTION_DOWNLOAD_RIGHTS;
			HRESULT nS_E_MEDIA_NOT_PURCHASED;
			nS_E_MEDIA_NOT_PURCHASED.hr = -1072884891;
			_NS_E_MEDIA_NOT_PURCHASED = nS_E_MEDIA_NOT_PURCHASED;
			HRESULT nS_E_MESSAGING_CLIENT_ERROR;
			nS_E_MESSAGING_CLIENT_ERROR.hr = -1072885517;
			_NS_E_MESSAGING_CLIENT_ERROR = nS_E_MESSAGING_CLIENT_ERROR;
			HRESULT nS_E_MESSAGING_RECIPIENT_ERROR;
			nS_E_MESSAGING_RECIPIENT_ERROR.hr = -1072885515;
			_NS_E_MESSAGING_RECIPIENT_ERROR = nS_E_MESSAGING_RECIPIENT_ERROR;
			HRESULT nS_E_MESSAGING_PARENTAL_CONTROL_ERROR;
			nS_E_MESSAGING_PARENTAL_CONTROL_ERROR.hr = -1072885513;
			_NS_E_MESSAGING_PARENTAL_CONTROL_ERROR = nS_E_MESSAGING_PARENTAL_CONTROL_ERROR;
			HRESULT nS_E_CART_FULL;
			nS_E_CART_FULL.hr = -1072885493;
			_NS_E_CART_FULL = nS_E_CART_FULL;
			HRESULT nS_E_CART_TOO_MANY_NEW_ITEMS;
			nS_E_CART_TOO_MANY_NEW_ITEMS.hr = -1072885492;
			_NS_E_CART_TOO_MANY_NEW_ITEMS = nS_E_CART_TOO_MANY_NEW_ITEMS;
			HRESULT nS_E_CART_MORE_ITEMS_AVAILABLE;
			nS_E_CART_MORE_ITEMS_AVAILABLE.hr = -2146627315;
			_NS_E_CART_MORE_ITEMS_AVAILABLE = nS_E_CART_MORE_ITEMS_AVAILABLE;
			HRESULT nS_E_SIGNIN_TERMS_OF_SERVICE;
			nS_E_SIGNIN_TERMS_OF_SERVICE.hr = -1072884874;
			_NS_E_SIGNIN_TERMS_OF_SERVICE = nS_E_SIGNIN_TERMS_OF_SERVICE;
			HRESULT nS_E_SERVER_ACCESSDENIED;
			nS_E_SERVER_ACCESSDENIED.hr = -1072877829;
			_NS_E_SERVER_ACCESSDENIED = nS_E_SERVER_ACCESSDENIED;
			HRESULT nS_E_PASSPORT_LOGIN_FAILED;
			nS_E_PASSPORT_LOGIN_FAILED.hr = -1072884892;
			_NS_E_PASSPORT_LOGIN_FAILED = nS_E_PASSPORT_LOGIN_FAILED;
			HRESULT nS_E_SUBSCRIPTIONSERVICE_LOGIN_FAILED;
			nS_E_SUBSCRIPTIONSERVICE_LOGIN_FAILED.hr = -1072884897;
			_NS_E_SUBSCRIPTIONSERVICE_LOGIN_FAILED = nS_E_SUBSCRIPTIONSERVICE_LOGIN_FAILED;
			HRESULT nS_E_INVALID_USERNAME_AND_PASSWORD;
			nS_E_INVALID_USERNAME_AND_PASSWORD.hr = -1072884910;
			_NS_E_INVALID_USERNAME_AND_PASSWORD = nS_E_INVALID_USERNAME_AND_PASSWORD;
			HRESULT nS_E_SIGNIN_ACCOUNTS_INVALID_USER;
			nS_E_SIGNIN_ACCOUNTS_INVALID_USER.hr = -1072884884;
			_NS_E_SIGNIN_ACCOUNTS_INVALID_USER = nS_E_SIGNIN_ACCOUNTS_INVALID_USER;
			HRESULT nS_E_SIGNIN_ACCOUNTS_NOT_XENON_USER;
			nS_E_SIGNIN_ACCOUNTS_NOT_XENON_USER.hr = -1072884882;
			_NS_E_SIGNIN_ACCOUNTS_NOT_XENON_USER = nS_E_SIGNIN_ACCOUNTS_NOT_XENON_USER;
			HRESULT nS_E_SIGNIN_WCMUSIC_ACCOUNT_NOT_ELIGIBLE;
			nS_E_SIGNIN_WCMUSIC_ACCOUNT_NOT_ELIGIBLE.hr = -1072884883;
			_NS_E_SIGNIN_WCMUSIC_ACCOUNT_NOT_ELIGIBLE = nS_E_SIGNIN_WCMUSIC_ACCOUNT_NOT_ELIGIBLE;
			HRESULT zUNE_E_SIGNIN_TERMS_OF_SERVICE_CHILD;
			zUNE_E_SIGNIN_TERMS_OF_SERVICE_CHILD.hr = -1056899049;
			_ZUNE_E_SIGNIN_TERMS_OF_SERVICE_CHILD = zUNE_E_SIGNIN_TERMS_OF_SERVICE_CHILD;
			HRESULT nS_E_SIGNIN_INVALID_REGION;
			nS_E_SIGNIN_INVALID_REGION.hr = -1072884909;
			_NS_E_SIGNIN_INVALID_REGION = nS_E_SIGNIN_INVALID_REGION;
			HRESULT zEST_E_UNAUTHENTICATED;
			zEST_E_UNAUTHENTICATED.hr = -1056858108;
			_ZEST_E_UNAUTHENTICATED = zEST_E_UNAUTHENTICATED;
			HRESULT nS_E_SIGNIN_HTTP_GONE;
			nS_E_SIGNIN_HTTP_GONE.hr = -1072885082;
			_NS_E_SIGNIN_HTTP_GONE = nS_E_SIGNIN_HTTP_GONE;
			HRESULT nS_E_BILLING_LIGHTWEIGHT_ACCOUNT;
			nS_E_BILLING_LIGHTWEIGHT_ACCOUNT.hr = -1072885473;
			_NS_E_BILLING_LIGHTWEIGHT_ACCOUNT = nS_E_BILLING_LIGHTWEIGHT_ACCOUNT;
			HRESULT nS_E_FIRMWARE_UPDATE_DISK_FULL;
			nS_E_FIRMWARE_UPDATE_DISK_FULL.hr = -1072885167;
			_NS_E_FIRMWARE_UPDATE_DISK_FULL = nS_E_FIRMWARE_UPDATE_DISK_FULL;
			HRESULT nS_E_WINLIVE_SIGNIN_NAME_TOO_SHORT;
			nS_E_WINLIVE_SIGNIN_NAME_TOO_SHORT.hr = -1072875780;
			_NS_E_WINLIVE_SIGNIN_NAME_TOO_SHORT = nS_E_WINLIVE_SIGNIN_NAME_TOO_SHORT;
			HRESULT nS_E_WINLIVE_SIGNIN_NAME_TOO_LONG;
			nS_E_WINLIVE_SIGNIN_NAME_TOO_LONG.hr = -1072875804;
			_NS_E_WINLIVE_SIGNIN_NAME_TOO_LONG = nS_E_WINLIVE_SIGNIN_NAME_TOO_LONG;
			HRESULT nS_E_WINLIVE_SIGNIN_NAME_INVALID;
			nS_E_WINLIVE_SIGNIN_NAME_INVALID.hr = -1072875803;
			_NS_E_WINLIVE_SIGNIN_NAME_INVALID = nS_E_WINLIVE_SIGNIN_NAME_INVALID;
			HRESULT nS_E_WINLIVE_EMAIL_INVALID;
			nS_E_WINLIVE_EMAIL_INVALID.hr = -1072875802;
			_NS_E_WINLIVE_EMAIL_INVALID = nS_E_WINLIVE_EMAIL_INVALID;
			HRESULT nS_E_WINLIVE_NAME_INVALID;
			nS_E_WINLIVE_NAME_INVALID.hr = -1072875801;
			_NS_E_WINLIVE_NAME_INVALID = nS_E_WINLIVE_NAME_INVALID;
			HRESULT nS_E_WINLIVE_BIRTH_YEAR_INVALID;
			nS_E_WINLIVE_BIRTH_YEAR_INVALID.hr = -1072875800;
			_NS_E_WINLIVE_BIRTH_YEAR_INVALID = nS_E_WINLIVE_BIRTH_YEAR_INVALID;
			HRESULT nS_E_WINLIVE_BIRTH_DAY_INVALID;
			nS_E_WINLIVE_BIRTH_DAY_INVALID.hr = -1072875799;
			_NS_E_WINLIVE_BIRTH_DAY_INVALID = nS_E_WINLIVE_BIRTH_DAY_INVALID;
			HRESULT nS_E_WINLIVE_BIRTH_MONTH_INVALID;
			nS_E_WINLIVE_BIRTH_MONTH_INVALID.hr = -1072875798;
			_NS_E_WINLIVE_BIRTH_MONTH_INVALID = nS_E_WINLIVE_BIRTH_MONTH_INVALID;
			HRESULT nS_E_WINLIVE_BIRTH_DATE_FUTURE;
			nS_E_WINLIVE_BIRTH_DATE_FUTURE.hr = -1072875797;
			_NS_E_WINLIVE_BIRTH_DATE_FUTURE = nS_E_WINLIVE_BIRTH_DATE_FUTURE;
			HRESULT nS_E_WINLIVE_HIP_SOLUTION_INVALID;
			nS_E_WINLIVE_HIP_SOLUTION_INVALID.hr = -1072875796;
			_NS_E_WINLIVE_HIP_SOLUTION_INVALID = nS_E_WINLIVE_HIP_SOLUTION_INVALID;
			HRESULT nS_E_WINLIVE_PASSWORD_TOO_LONG;
			nS_E_WINLIVE_PASSWORD_TOO_LONG.hr = -1072875795;
			_NS_E_WINLIVE_PASSWORD_TOO_LONG = nS_E_WINLIVE_PASSWORD_TOO_LONG;
			HRESULT nS_E_WINLIVE_PASSWORD_TOO_SHORT;
			nS_E_WINLIVE_PASSWORD_TOO_SHORT.hr = -1072875794;
			_NS_E_WINLIVE_PASSWORD_TOO_SHORT = nS_E_WINLIVE_PASSWORD_TOO_SHORT;
			HRESULT nS_E_WINLIVE_PASSWORD_INVALID;
			nS_E_WINLIVE_PASSWORD_INVALID.hr = -1072875793;
			_NS_E_WINLIVE_PASSWORD_INVALID = nS_E_WINLIVE_PASSWORD_INVALID;
			HRESULT nS_E_WINLIVE_MEMBER_EXISTS;
			nS_E_WINLIVE_MEMBER_EXISTS.hr = -1072875792;
			_NS_E_WINLIVE_MEMBER_EXISTS = nS_E_WINLIVE_MEMBER_EXISTS;
			HRESULT nS_E_WINLIVE_DOMAIN_IS_MANAGED;
			nS_E_WINLIVE_DOMAIN_IS_MANAGED.hr = -1072875791;
			_NS_E_WINLIVE_DOMAIN_IS_MANAGED = nS_E_WINLIVE_DOMAIN_IS_MANAGED;
			HRESULT nS_E_WINLIVE_SECRET_QUESTION_TOO_SHORT;
			nS_E_WINLIVE_SECRET_QUESTION_TOO_SHORT.hr = -1072875790;
			_NS_E_WINLIVE_SECRET_QUESTION_TOO_SHORT = nS_E_WINLIVE_SECRET_QUESTION_TOO_SHORT;
			HRESULT nS_E_WINLIVE_SECRET_QUESTION_TOO_LONG;
			nS_E_WINLIVE_SECRET_QUESTION_TOO_LONG.hr = -1072875789;
			_NS_E_WINLIVE_SECRET_QUESTION_TOO_LONG = nS_E_WINLIVE_SECRET_QUESTION_TOO_LONG;
			HRESULT nS_E_WINLIVE_SECRET_ANSWER_TOO_SHORT;
			nS_E_WINLIVE_SECRET_ANSWER_TOO_SHORT.hr = -1072875788;
			_NS_E_WINLIVE_SECRET_ANSWER_TOO_SHORT = nS_E_WINLIVE_SECRET_ANSWER_TOO_SHORT;
			HRESULT nS_E_WINLIVE_SECRET_ANSWER_TOO_LONG;
			nS_E_WINLIVE_SECRET_ANSWER_TOO_LONG.hr = -1072875787;
			_NS_E_WINLIVE_SECRET_ANSWER_TOO_LONG = nS_E_WINLIVE_SECRET_ANSWER_TOO_LONG;
			HRESULT nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_ANSWER;
			nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_ANSWER.hr = -1072875786;
			_NS_E_WINLIVE_SECRET_QUESTION_CONTAINS_ANSWER = nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_ANSWER;
			HRESULT nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_MEMBER_NAME;
			nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_MEMBER_NAME.hr = -1072875785;
			_NS_E_WINLIVE_SECRET_ANSWER_CONTAINS_MEMBER_NAME = nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_MEMBER_NAME;
			HRESULT nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_PASSWORD;
			nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_PASSWORD.hr = -1072875784;
			_NS_E_WINLIVE_SECRET_ANSWER_CONTAINS_PASSWORD = nS_E_WINLIVE_SECRET_ANSWER_CONTAINS_PASSWORD;
			HRESULT nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_PASSWORD;
			nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_PASSWORD.hr = -1072875783;
			_NS_E_WINLIVE_SECRET_QUESTION_CONTAINS_PASSWORD = nS_E_WINLIVE_SECRET_QUESTION_CONTAINS_PASSWORD;
			HRESULT zUNE_E_WINLIVE_UNAUTHORIZED_DOMAIN;
			zUNE_E_WINLIVE_UNAUTHORIZED_DOMAIN.hr = -1056899039;
			_ZUNE_E_WINLIVE_UNAUTHORIZED_DOMAIN = zUNE_E_WINLIVE_UNAUTHORIZED_DOMAIN;
			HRESULT zEST_E_ACCOUNT_ZUNETAG_OCCUPIED;
			zEST_E_ACCOUNT_ZUNETAG_OCCUPIED.hr = -1056857549;
			_ZEST_E_ACCOUNT_ZUNETAG_OCCUPIED = zEST_E_ACCOUNT_ZUNETAG_OCCUPIED;
			HRESULT zUNE_E_SIGNUP_INVALID_PARENT_EMAIL;
			zUNE_E_SIGNUP_INVALID_PARENT_EMAIL.hr = -1056899047;
			_ZUNE_E_SIGNUP_INVALID_PARENT_EMAIL = zUNE_E_SIGNUP_INVALID_PARENT_EMAIL;
			HRESULT zUNE_E_SIGNUP_INVALID_PARENT_AGE;
			zUNE_E_SIGNUP_INVALID_PARENT_AGE.hr = -1056899046;
			_ZUNE_E_SIGNUP_INVALID_PARENT_AGE = zUNE_E_SIGNUP_INVALID_PARENT_AGE;
			HRESULT zUNE_E_SIGNUP_PASSWORDS_DONT_MATCH;
			zUNE_E_SIGNUP_PASSWORDS_DONT_MATCH.hr = -1056899045;
			_ZUNE_E_SIGNUP_PASSWORDS_DONT_MATCH = zUNE_E_SIGNUP_PASSWORDS_DONT_MATCH;
			HRESULT zUNE_E_UPDATE_ACCOUNT_INFO_FAILED;
			zUNE_E_UPDATE_ACCOUNT_INFO_FAILED.hr = -1056899040;
			_ZUNE_E_UPDATE_ACCOUNT_INFO_FAILED = zUNE_E_UPDATE_ACCOUNT_INFO_FAILED;
			HRESULT zEST_E_INVALID_POSTALCODE;
			zEST_E_INVALID_POSTALCODE.hr = -1056857603;
			_ZEST_E_INVALID_POSTALCODE = zEST_E_INVALID_POSTALCODE;
			HRESULT zEST_E_LIVEACCOUNT_INVALIDPHONE;
			zEST_E_LIVEACCOUNT_INVALIDPHONE.hr = -1056857601;
			_ZEST_E_LIVEACCOUNT_INVALIDPHONE = zEST_E_LIVEACCOUNT_INVALIDPHONE;
			HRESULT zEST_E_LIVEACCOUNT_ADDRESS_INVALID;
			zEST_E_LIVEACCOUNT_ADDRESS_INVALID.hr = -1056857537;
			_ZEST_E_LIVEACCOUNT_ADDRESS_INVALID = zEST_E_LIVEACCOUNT_ADDRESS_INVALID;
			HRESULT zEST_E_LIVEACCOUNT_PAYMENT_INSTRUMENT_INVALID;
			zEST_E_LIVEACCOUNT_PAYMENT_INSTRUMENT_INVALID.hr = -1056857540;
			_ZEST_E_LIVEACCOUNT_PAYMENT_INSTRUMENT_INVALID = zEST_E_LIVEACCOUNT_PAYMENT_INSTRUMENT_INVALID;
			HRESULT zEST_E_CREDITCARD_ADDRESS_INVALID;
			zEST_E_CREDITCARD_ADDRESS_INVALID.hr = -1056857570;
			_ZEST_E_CREDITCARD_ADDRESS_INVALID = zEST_E_CREDITCARD_ADDRESS_INVALID;
			HRESULT zEST_E_CREDITCARD_ADDRESS_STREET1_INVALID;
			zEST_E_CREDITCARD_ADDRESS_STREET1_INVALID.hr = -1056857568;
			_ZEST_E_CREDITCARD_ADDRESS_STREET1_INVALID = zEST_E_CREDITCARD_ADDRESS_STREET1_INVALID;
			HRESULT zEST_E_CREDITCARD_ADDRESS_CITY_INVALID;
			zEST_E_CREDITCARD_ADDRESS_CITY_INVALID.hr = -1056857567;
			_ZEST_E_CREDITCARD_ADDRESS_CITY_INVALID = zEST_E_CREDITCARD_ADDRESS_CITY_INVALID;
			HRESULT zEST_E_CREDITCARD_ADDRESS_STATE_INVALID;
			zEST_E_CREDITCARD_ADDRESS_STATE_INVALID.hr = -1056857566;
			_ZEST_E_CREDITCARD_ADDRESS_STATE_INVALID = zEST_E_CREDITCARD_ADDRESS_STATE_INVALID;
			HRESULT zEST_E_CREDITCARD_ADDRESS_POSTALCODE_INVALID;
			zEST_E_CREDITCARD_ADDRESS_POSTALCODE_INVALID.hr = -1056857565;
			_ZEST_E_CREDITCARD_ADDRESS_POSTALCODE_INVALID = zEST_E_CREDITCARD_ADDRESS_POSTALCODE_INVALID;
			HRESULT zEST_E_CREDITCARD_PARENTPHONE_INVALID;
			zEST_E_CREDITCARD_PARENTPHONE_INVALID.hr = -1056857564;
			_ZEST_E_CREDITCARD_PARENTPHONE_INVALID = zEST_E_CREDITCARD_PARENTPHONE_INVALID;
			HRESULT zEST_E_CREDITCARD_INVALID;
			zEST_E_CREDITCARD_INVALID.hr = -1056857563;
			_ZEST_E_CREDITCARD_INVALID = zEST_E_CREDITCARD_INVALID;
			HRESULT zEST_E_CREDITCARD_VALIDATE_FAILED;
			zEST_E_CREDITCARD_VALIDATE_FAILED.hr = -1056857562;
			_ZEST_E_CREDITCARD_VALIDATE_FAILED = zEST_E_CREDITCARD_VALIDATE_FAILED;
			HRESULT zEST_E_CREDITCARD_ADD_FAILED;
			zEST_E_CREDITCARD_ADD_FAILED.hr = -1056857561;
			_ZEST_E_CREDITCARD_ADD_FAILED = zEST_E_CREDITCARD_ADD_FAILED;
			HRESULT zEST_E_INVALID_ARG_ZUNETAG;
			zEST_E_INVALID_ARG_ZUNETAG.hr = -1056858064;
			_ZEST_E_INVALID_ARG_ZUNETAG = zEST_E_INVALID_ARG_ZUNETAG;
			HRESULT zEST_E_INVALID_ARG_PARENT_PHONE_INVALID;
			zEST_E_INVALID_ARG_PARENT_PHONE_INVALID.hr = -1056858078;
			_ZEST_E_INVALID_ARG_PARENT_PHONE_INVALID = zEST_E_INVALID_ARG_PARENT_PHONE_INVALID;
			HRESULT zEST_E_INVALID_ARG_CONTACT_INFO;
			zEST_E_INVALID_ARG_CONTACT_INFO.hr = -1056858076;
			_ZEST_E_INVALID_ARG_CONTACT_INFO = zEST_E_INVALID_ARG_CONTACT_INFO;
			HRESULT zEST_E_INVALID_ARG_LANGUAGE;
			zEST_E_INVALID_ARG_LANGUAGE.hr = -1056858057;
			_ZEST_E_INVALID_ARG_LANGUAGE = zEST_E_INVALID_ARG_LANGUAGE;
			HRESULT zEST_E_ZUNETAG_OFFENSIVE;
			zEST_E_ZUNETAG_OFFENSIVE.hr = -1056857522;
			_ZEST_E_ZUNETAG_OFFENSIVE = zEST_E_ZUNETAG_OFFENSIVE;
			HRESULT zUNE_E_PURCHASE_REQUIRES_AUTHORIZATION;
			zUNE_E_PURCHASE_REQUIRES_AUTHORIZATION.hr = -1056899019;
			_ZUNE_E_PURCHASE_REQUIRES_AUTHORIZATION = zUNE_E_PURCHASE_REQUIRES_AUTHORIZATION;
			HRESULT zEST_E_PARTNER_SERVICE_UNKNOWN_ERROR;
			zEST_E_PARTNER_SERVICE_UNKNOWN_ERROR.hr = -1056848896;
			_ZEST_E_PARTNER_SERVICE_UNKNOWN_ERROR = zEST_E_PARTNER_SERVICE_UNKNOWN_ERROR;
			HRESULT nS_E_DRM_RENTAL_LICENSE_EXPIRED;
			nS_E_DRM_RENTAL_LICENSE_EXPIRED.hr = -1072879537;
			_NS_E_DRM_RENTAL_LICENSE_EXPIRED = nS_E_DRM_RENTAL_LICENSE_EXPIRED;
			HRESULT nS_E_DRM_LICENSE_ALREADY_ACQUIRED;
			nS_E_DRM_LICENSE_ALREADY_ACQUIRED.hr = -1072879536;
			_NS_E_DRM_LICENSE_ALREADY_ACQUIRED = nS_E_DRM_LICENSE_ALREADY_ACQUIRED;
			HRESULT nS_E_DRM_DEVICE_RENTAL_LICENSE;
			nS_E_DRM_DEVICE_RENTAL_LICENSE.hr = -1072879535;
			_NS_E_DRM_DEVICE_RENTAL_LICENSE = nS_E_DRM_DEVICE_RENTAL_LICENSE;
			HRESULT zUNE_E_CONTENT_NOT_SUPPORTED_ON_TUNER;
			zUNE_E_CONTENT_NOT_SUPPORTED_ON_TUNER.hr = -1056899034;
			_ZUNE_E_CONTENT_NOT_SUPPORTED_ON_TUNER = zUNE_E_CONTENT_NOT_SUPPORTED_ON_TUNER;
			HRESULT zUNE_E_QUICKMIX_MEDIA_NOT_FOUND;
			zUNE_E_QUICKMIX_MEDIA_NOT_FOUND.hr = -1056898969;
			_ZUNE_E_QUICKMIX_MEDIA_NOT_FOUND = zUNE_E_QUICKMIX_MEDIA_NOT_FOUND;
			HRESULT zUNE_E_QUICKMIX_SESSION_IN_USE;
			zUNE_E_QUICKMIX_SESSION_IN_USE.hr = -1056898964;
			_ZUNE_E_QUICKMIX_SESSION_IN_USE = zUNE_E_QUICKMIX_SESSION_IN_USE;
			HRESULT zUNE_E_UNKNOWN_REGION_OR_LANGUAGE;
			zUNE_E_UNKNOWN_REGION_OR_LANGUAGE.hr = -1056899029;
			_ZUNE_E_UNKNOWN_REGION_OR_LANGUAGE = zUNE_E_UNKNOWN_REGION_OR_LANGUAGE;
			HRESULT nS_E_CURL_INVALIDCHAR;
			nS_E_CURL_INVALIDCHAR.hr = -1072884955;
			_NS_E_CURL_INVALIDCHAR = nS_E_CURL_INVALIDCHAR;
			HRESULT nS_E_CURL_INVALIDPATH;
			nS_E_CURL_INVALIDPATH.hr = -1072884953;
			_NS_E_CURL_INVALIDPATH = nS_E_CURL_INVALIDPATH;
			HRESULT zUNE_E_ADD_REVIEW_FAILED;
			zUNE_E_ADD_REVIEW_FAILED.hr = -1056898960;
			_ZUNE_E_ADD_REVIEW_FAILED = zUNE_E_ADD_REVIEW_FAILED;
			HRESULT zEST_E_MAX_CONCURRENTSTREAMING_EXCEEDED;
			zEST_E_MAX_CONCURRENTSTREAMING_EXCEEDED.hr = -1056856102;
			_ZEST_E_MAX_CONCURRENTSTREAMING_EXCEEDED = zEST_E_MAX_CONCURRENTSTREAMING_EXCEEDED;
			HRESULT zEST_E_MULTITUNER_CONCURRENTSTREAMING_DETECTED;
			zEST_E_MULTITUNER_CONCURRENTSTREAMING_DETECTED.hr = -1056856104;
			_ZEST_E_MULTITUNER_CONCURRENTSTREAMING_DETECTED = zEST_E_MULTITUNER_CONCURRENTSTREAMING_DETECTED;
			HRESULT zEST_E_MEDIAINSTANCE_STREAMING_OCCUPIED;
			zEST_E_MEDIAINSTANCE_STREAMING_OCCUPIED.hr = -1056856095;
			_ZEST_E_MEDIAINSTANCE_STREAMING_OCCUPIED = zEST_E_MEDIAINSTANCE_STREAMING_OCCUPIED;
		}
	}
}
