public enum EListType
{
	eListTypeCount = 23,
	eLicenseList = 22,
	ePinList = 21,
	eAppList = 20,
	eUserCardPlaylistList = 19,
	eUserCardList = 18,
	eUserList = 17,
	eSubscriptionList = 0x10,
	eGenreList = 0xF,
	eDiscMediaContentList = 14,
	ePlaylistContentList = 13,
	ePlaylistList = 12,
	eDeviceContentList = 11,
	eFolderList = 10,
	eFileList = 9,
	eDeviceFirmwareList = 8,
	ePodcastEpisodeList = 7,
	ePodcastList = 6,
	eDeviceList = 5,
	eVideoList = 4,
	ePhotoList = 3,
	eTrackList = 2,
	eAlbumList = 1,
	eArtistList = 0,
	eListInvalid = -1
}
