// Declared in the global namespace to match the original ZuneDBApi.dll metadata
// (ILSpy reports this type with an empty namespace, like EMediaTypes.cs — see that
// file's header comment for the full rationale). Placed at the project root rather
// than under a namespace-mapped folder for that reason.
public enum EQueryType
{
    eQueryTypeInvalid = -1,
    eQueryTypeAllTracks = 0,
    eQueryTypeAllTracksDetailed = 1,
    eQueryTypeAllVideos = 2,
    eQueryTypeAllVideosDetailed = 3,
    eQueryTypeAllPhotos = 4,
    eQueryTypeAllAlbums = 5,
    eQueryTypeAllAlbumArtists = 6,
    eQueryTypeAllPodcastSeries = 7,
    eQueryTypeAllPodcastEpisodes = 8,
    eQueryTypeAlbumsForAlbumArtistId = 9,
    eQueryTypeTracksForAlbumId = 10,
    eQueryTypeTracksForAlbumArtistId = 11,
    eQueryTypeEpisodesForSeriesId = 12,
    eQueryTypeAlbumsByTOC = 13,
    eQueryTypeAlbumsWithKeyword = 14,
    eQueryTypeTracksWithKeyword = 15,
    eQueryTypeArtistsWithKeyword = 16,
    eQueryTypePlaylistsWithKeyword = 17,
    eQueryTypePhotosWithKeyword = 18,
    eQueryTypeSubscriptionsSeriesWithKeyword = 19,
    eQueryTypeSubscriptionsEpisodesWithKeyword = 20,
    eQueryTypeVideoWithKeyword = 21,
    eQueryTypeMediaFolders = 22,
    eQueryTypePhotosByFolderId = 23,
    eQueryTypeVideosByFolderId = 24,
    eQueryTypeVideosByCategoryId = 25,
    eQueryTypeSyncProgress = 26,
    eQueryTypeAllPlaylists = 27,
    eQueryTypePlaylistContentByPlaylistId = 28,
    eQueryTypeAllGenres = 29,
    eQueryTypeTracksByGenreId = 30,
    eQueryTypeAlbumsByGenreId = 31,
    eQueryTypeUserCards = 32,
    eQueryTypeTracksForTOC = 33,
    eQueryTypePersonsByTypeId = 34,
    eQueryTypeVideoSeriesTitles = 35,
    eQueryTypeFilesByTrackId = 36,
    eQueryTypePinsByPinType = 37,
    eQueryTypeAllApps = 38,
    eQueryTypeArtistsRanking = 39,
}
