// Declared in the global namespace to match the original ZuneDBApi.dll metadata
// (ILSpy reports this type with an empty namespace, like EMediaTypes.cs — see that
// file's header comment for the full rationale).
public enum Features
{
    eQuickplay = 0,
    eDevice = 1,
    eMarketplace = 2,
    ePicks = 3,
    eVideos = 4,
    eSocial = 5,
    eMusicVideos = 6,
    ePodcasts = 7,
    eChannels = 8,
    eRadio = 9,
    eGames = 10,
    eApps = 11,
    eTV = 12,
    eMovieTrailers = 13,
    eSubscription = 14,
    eSubscriptionConfirmation = 15,
    eSubscriptionFreeTracks = 16,
    eSubscriptionTrial = 17,
    eSubscriptionMusicDownload = 18,
    eSubscriptionMusicVideoStreaming = 19,
    eSignInAvailable = 20,
    eFirstLaunchIntroVideo = 21,
    eMBRRental = 22,
    eMBRPurchase = 23,
    eMBRPreview = 24,
    eOptIn = 25,
    eQuickMixLocal = 26,
    eQuickMixZmp = 27,
    eMusic = 28,
    eMixview = 29,
    eSocialMarketplace = 30,
    eVideoAllHub = 31,
    eLastFeature = 32,
}
