<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>ZuneDBApi</AssemblyName>
        <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
        <TargetFrameworks>$(MinimalTargetFrameworks)</TargetFrameworks>
        <PlatformTarget>x64</PlatformTarget>
        <LangVersion>12.0</LangVersion>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\libs\MicrosoftIris\UIX\UIX.csproj" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    </ItemGroup>
</Project>