<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\libs\ZuneUIXTools\libs\MicrosoftIris\UIX\UIX.csproj" />
    </ItemGroup>

</Project>
