# Usage: extractMuiStrings.sh [muiFile] [outputCs] [namespace] [className]
# Reads the RT_STRING (STRINGTABLE) resources out of a Win32 MUI satellite
# resource file and generates a C# class mapping resource ID -> string.

MUI_FILE=${1:-../../windows/shared/zune-x64/Zune/en-US/ZuneResources.dll.mui}
OUT_CS=${2:-../ZuneDBApi/MicrosoftZuneLibrary/ZuneLibraryResources.g.cs}
NAMESPACE=${3:-MicrosoftZuneLibrary}
CLASS_NAME=${4:-ZuneLibraryResources}

for cmd in wrestool od dd iconv awk; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "$cmd is required but was not found on PATH." >&2; exit 1; }
done

if [ ! -f "$MUI_FILE" ]; then
    echo "MUI file not found: $MUI_FILE" >&2
    exit 1
fi

echo "Extracting RT_STRING resources from $MUI_FILE..."

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

mkdir -p "$(dirname "$OUT_CS")"

{
    echo "// <auto-generated>"
    echo "// Generated by Scripts/extractMuiStrings.sh from $(basename "$MUI_FILE"). Do not edit by hand."
    echo "// </auto-generated>"
    echo
    echo "using System.Collections.Generic;"
    echo
    echo "namespace $NAMESPACE;"
    echo
    echo "public static class $CLASS_NAME"
    echo "{"
    echo "    public static readonly IReadOnlyDictionary<uint, string> Strings = new Dictionary<uint, string>"
    echo "    {"
} > "$OUT_CS"

# Each RT_STRING block (resource name N) holds ids (N-1)*16 .. (N-1)*16+15,
# each stored as a WORD char-count followed by that many UTF-16LE chars (no
# null terminator); a zero count marks an unused slot.
while read -r name lang; do
    raw="$TMP_DIR/$name.bin"
    wrestool --raw -x --type=6 --name="$name" --language="$lang" -o "$raw" "$MUI_FILE"
    size=$(stat -c%s "$raw")
    base_id=$(( (name - 1) * 16 ))
    offset=0

    for ((i = 0; i < 16; i++)); do
        (( offset + 2 > size )) && break

        length=$(od -An -tu2 --endian=little -j "$offset" -N 2 -- "$raw" | tr -d ' ')
        offset=$(( offset + 2 ))
        bytelen=$(( length * 2 ))

        if (( length > 0 )); then
            id=$(( base_id + i ))
            escaped=$(
                dd if="$raw" iflag=skip_bytes,count_bytes skip="$offset" count="$bytelen" 2>/dev/null \
                    | iconv -f UTF-16LE -t UTF-8 \
                    | awk 'BEGIN { RS = "\0" }
                           { gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); gsub(/\r/, "\\r"); gsub(/\n/, "\\n"); gsub(/\t/, "\\t"); printf "%s", $0 }'
            )
            printf '        [%d] = "%s",\n' "$id" "$escaped" >> "$OUT_CS"
        fi

        offset=$(( offset + bytelen ))
    done
done < <(
    wrestool -l --type=6 "$MUI_FILE" \
        | grep -oE -- '--name=[0-9]+ --language=[0-9]+' \
        | sed -E 's/--name=([0-9]+) --language=([0-9]+)/\1 \2/' \
        | sort -n -k1,1
)

{
    echo "    };"
    echo "}"
} >> "$OUT_CS"

echo "Wrote $(grep -c '] = "' "$OUT_CS") strings to $OUT_CS"
